
#' Plot Scores for Multivariate Models
#'
#'  This function generates a scores plot for multivariate models created using the `ropls` package,
#' including PCA, PLS(-DA), and OPLS(-DA). It provides advanced customization options for visualization
#' using `ggplot2`, allowing the addition of ellipses, sample labels, and group-based coloring.
#'
#' @param model A list containing a model of type PCA, PLS-DA, OPLS-DA, PLS, or OPLS, generated by the `ropls` package.
#' @param groups A vector specifying sample groups used for coloring and identifying samples in PCA models.
#' In supervised models (PLS-DA, OPLS-DA), the groups are automatically defined by the model.
#' @param comp A numeric vector of length 2 specifying the components to be plotted. Defaults to `c(1, 2)`.
#' @param point_size Numeric. Defines the size of the points in the plot (default: `2`).
#' @param ellipse Logical. If `TRUE`, confidence interval ellipses are displayed around groups (default: `TRUE`).
#' @param labels  Logical or vector. If `TRUE`, sample names are displayed as labels.
#' Alternatively, a custom vector of sample names can be provided. If `FALSE`, no labels are shown (default: `TRUE`).
#' @param font.label A vector specifying the font size, color, and style for sample labels. For details, see
#' the `font.label` argument in the `ggscatter` function from the `ggpubr` package.
#' @param point Logical. If `TRUE`, points representing samples are displayed in the plot (default: `TRUE`).
#' @param repel_labels Logical. If `TRUE`, sample labels are adjusted to avoid overlap (default: `FALSE`).
#' @param theme A ggplot2 theme for customizing the plot appearance. If `NULL`, the default theme `theme_bw` is used.
#'
#' @description
#'  Provides an easy way to generate scores plots from models generated by the `ropls` package,
#' with advanced customization options such as group-based coloring, confidence ellipses,
#' and flexible label positioning.
#'
#' @return
#' A `ggplot2` object representing the scores plot for the specified multivariate model.
#'
#' @export
#'
#' @examples \dontrun{
#' # Example usage:
#' model <- some_ropls_model   # Replace with your PCA, PLS-DA, or OPLS-DA model
#' groups <- c("Group1", "Group2", "Group1", "Group2")  # Define sample groups for coloring
#' Plot_scores(model, groups = groups, comp = c(1, 2), ellipse = TRUE, labels = TRUE)
#'}
#'
Plot_scores <- function(model,groups=NULL,comp=c(1,2),point_size=2,ellipse=T,labels=T,font.label=c(12,"plain"),point=T,repel_labels=F,theme=NULL){

  if(model@typeC=="PCA"){

    PCA_data <- extract_ropls_data(model)
    legend.text=F

    if(!is.null(groups)){
      PCA_data$Scores$Group <- groups
      Group <- "Group"
      col_group <- Group
      group_alpha=0.3
      Legend=T
    }else{
      col_group = "black"
      Group <- NULL
      group_alpha=0
      Legend=F
    }

    if(ellipse==F){
      group_alpha <- 0
    }

    if(length(labels)==1&&labels==T){
      plot_label="Samples"
    }else{
      if(length(labels)==1&&labels==F){
        plot_label=NULL
      }else{
        PCA_data$Scores$Samples <- labels
        plot_label="Samples"
      }
    }
    if(point==F){
      legend.text=NA
    }

    scores_plot <- ggpubr::ggscatter(PCA_data$Scores,x=paste("p",comp[1],sep = ""),y=paste("p",comp[2],sep = ""),color=col_group,
              size = point_size,label = plot_label,point = point,
              font.label = font.label,repel = repel_labels,show.legend.text = legend.text)+
      ggplot2::stat_ellipse(ggplot2::aes(color=if(ellipse==T) eval(Group),fill=if(ellipse==T) eval(Group)),geom = "polygon",
                            alpha=group_alpha,show.legend = F)+
      ggplot2::labs(x=paste("PC",comp[1]," (",model@modelDF$R2X[comp[1]]*100,"%)"),
           y=paste("PC",comp[2]," (",model@modelDF$R2X[comp[2]]*100,"%)"),
           title = model@typeC)+
      ggplot2::theme_bw()+ggplot2::theme(legend.text = ggplot2::element_text(size = 14),
                       axis.text = ggplot2::element_text(size=14),
                       axis.title = ggplot2::element_text(size = 14),
                       legend.position = "bottom")

  }

  if(model@typeC=="PLS-DA"||model@typeC=="PLS"){

    PLS_data <- extract_ropls_data(model)
    Group <- "Group"
    col_group <- Group
    group_alpha=0.3
    Legend=T
    legend.text=F

    if(ellipse==F){
      group_alpha <- 0
    }

    if(length(labels)==1&&labels==T){
      plot_label="Samples"
    }else{
      if(length(labels)==1&&labels==F){
        plot_label=NULL
      }else{
        PLS_data$Scores$Samples <- labels
        plot_label="Samples"
      }
    }
    if(point==F){
      legend.text=NA
    }

    scores_plot <- ggpubr::ggscatter(PLS_data$Scores,x=paste("p",comp[1],sep = ""),y=paste("p",comp[2],sep = ""),color=col_group,
                             size = point_size,label = plot_label,point = point,
                             font.label = font.label,repel = repel_labels,show.legend.text = legend.text)+
      ggplot2::stat_ellipse(ggplot2::aes(color=if(ellipse==T) eval(Group),fill=if(ellipse==T) eval(Group)),geom = "polygon",
                            alpha=group_alpha,show.legend = F)+
      ggplot2::labs(x=paste("Comp",comp[1]," (",model@modelDF$R2X[comp[1]]*100,"%)"),
           y=paste("Comp",comp[2]," (",model@modelDF$R2X[comp[2]]*100,"%)"),
           title = model@typeC)+
      ggplot2::theme_bw()+ggplot2::theme(legend.text = ggplot2::element_text(size = 14),
                       axis.text = ggplot2::element_text(size=14),
                       axis.title = ggplot2::element_text(size = 14),
                       legend.position = "bottom")

  }

  if(model@typeC=="OPLS-DA"||model@typeC=="OPLS"){

    PLS_data <- extract_ropls_data(model)
    Group <- "Group"
    col_group <- Group
    group_alpha=0.3
    Legend=T
    legend.text=F

    if(ellipse==F){
      group_alpha <- 0
    }

    if(length(labels)==1&&labels==T){
      plot_label="Samples"
    }else{
      if(length(labels)==1&&labels==F){
        plot_label=NULL
      }else{
        PLS_data$Scores$Samples <- labels
        plot_label="Samples"
      }
    }
    if(point==F){
      legend.text=NA
    }

    scores_plot <- ggpubr::ggscatter(PLS_data$Scores,
                                     x=if(comp[1]==1) paste("p",comp[1],sep = "") else paste("o",comp[1]-1,sep = ""),
                                     y= if(comp[2]==1) paste("p",comp[2],sep = "") else paste("o",comp[2]-1,sep = ""),
                                     color=col_group,
                                    size = point_size,label = plot_label,point = point,
                                    font.label = font.label,repel = repel_labels,show.legend.text = legend.text)+
                  ggplot2::stat_ellipse(ggplot2::aes(color=if(ellipse==T) eval(Group),fill=if(ellipse==T) eval(Group)),geom = "polygon",
                                                      alpha=group_alpha,show.legend = F)+
                  ggplot2::labs(x=paste(if(comp[1]==1) paste("Pred. Comp") else paste("Ortho. Comp"),comp[1]," (",model@modelDF$R2X[comp[1]]*100,"%)"),
                                y=paste(if(comp[2]==1) paste("Pred. Comp") else paste("Ortho. Comp"),comp[2]," (",model@modelDF$R2X[comp[2]]*100,"%)"),
                                title = model@typeC)+
                  ggplot2::theme_bw()+ggplot2::theme(legend.text = ggplot2::element_text(size = 14),
                                                      axis.text = ggplot2::element_text(size=14),
                                                      axis.title = ggplot2::element_text(size = 14),
                                                      legend.position = "bottom")

  }

  return(scores_plot+theme)
}



#' Generates multiple PCA score plots
#'
#' This function creates an overview of PCA scores, generating plots for each pair of principal components.
#'
#' @param PCA_object ropls PCA object containing the analysis results.
#' @param groups Vector of groups to color the points in the plots.
#' @param labels Vector of labels to identify the points in the plots.
#' @param label_size Font size for the labels. Default is 7.
#' @param plot_font_size Font size for the plot elements. Default is 7.
#' @param repel Logical. If `TRUE`, labels are repelled to avoid overlap. Default is `FALSE`.
#' @param show_points Logical. If `TRUE`, points are displayed in the plot. Default is `TRUE`.
#' @param add Additional elements to be added to the plots, such as scales, labels, or any other
#' ggplot2 element. For multiple elements provide a list containing the elements to be added. Default is `NULL`.
#' @param scale_expansion Axis expansion factor for the plots, used to avoid cliping sample names on plot margins. Default is 0.15.
#' @param return_list Logical. If `TRUE`, returns a list containing the ggplot2 objects to be used with wrap_plots().
#' if `FALSE` return a single combined plot. Default is `FALSE`.
#'
#' @return A single plot combining multiple pairs of principal components or a list of plots if `return_list = TRUE`.
#'
#'
#' @examples
#' \dontrun{
#'  Example usage:
#'  plot_scores_overview(PCA_object, groups = my_groups, labels = my_labels)
#'}
#'
#' @export
#'
plot_scores_overview <- function(PCA_object,
                                 groups,
                                 labels,
                                 label_size = 7,
                                 plot_font_size = 7,
                                 repel = F,
                                 show_points = T,
                                 add = NULL,
                                 scale_expansion = 0.15,
                                 return_list = F) {

  ncomps <- PCA_object@summaryDF$pre
  pca_scores_list <- list()

  for (i in seq(1, ncomps, 2)) {
    if (i == ncomps)
      break

    pca_scores_list[[length(pca_scores_list) + 1]] <- Plot_scores(
      PCA_object,
      groups = groups,
      ellipse = F,
      labels = labels,
      comp = c(i, i + 1),
      font.label = label_size,
      repel_labels = repel,
      point = show_points
    ) + ggplot2::theme(
      plot.title = ggplot2::element_blank(),
      axis.title = ggplot2::element_text(size = plot_font_size),
      legend.text = ggplot2::element_text(size = plot_font_size),
      legend.title = ggplot2::element_text(size = plot_font_size),
      axis.text = ggplot2::element_text(size = plot_font_size)
    ) + ggplot2::scale_x_continuous(expand = ggplot2::expansion(mult = scale_expansion)) +
        ggplot2::scale_y_continuous(expand = ggplot2::expansion(mult = scale_expansion)) +
      add
  }

  if (return_list) {
    return(pca_scores_list)
  } else{
    patchwork::wrap_plots(pca_scores_list)
  }
}

#'  Plot Loadings for Multivariate Models
#'
#'  This function generates a scatter plot of loadings for multivariate models, including PCA, PLS(-DA), and OPLS(-DA).
#' The function allows for customization of various plot parameters, enabling the identification and visualization
#' of important features (e.g., bins or metabolites) within the model. It supports options to label identified bins,
#' control the precision of rounding for bin and VIP values, and apply custom themes.
#'
#' @param model An object of class `ropls`, representing the multivariate model (PCA, PLS(-DA), or OPLS(-DA)) for which loadings are plotted.
#' @param comp A numeric vector of length 2 indicating the components to be plotted (default: `c(1, 2)`).
#' @param point Logical. If `TRUE`, points are displayed in the plot (default: `TRUE`).
#' @param repel Logical. If `TRUE`, labels are adjusted to repel each other, reducing overlap (default: `FALSE`).
#' @param font.label A vector indicating the font size and style of labels (e.g., `c(12, "plain")`).
#' @param bin_identification A data frame with two columns: the first column for metabolite names and the second for corresponding bins. Used to annotate bins.
#' @param bins_roundPrecision Integer. Specifies the number of decimal places for rounding bin values (default: `4`).
#' @param VIP_roundPrecision Integer. Specifies the number of decimal places for rounding VIP (Variable Importance in Projection) values (default: `2`).
#' @param show_metabolite_name Logical. If `TRUE`, metabolite names are displayed in labels when `bin_identification` is provided (default: `TRUE`).
#' @param VIP_values_scale A numeric vector of values to scale the color gradient for VIP values. If `NULL`, a default scale is applied. Use a vector of length 3 were the first value represents
#' the lower point of the scale, followed by the middle point and the highest point.
#' @param theme A ggplot2 theme to customize the plot appearance. If `NULL`, the default `theme_bw` is used.
#'
#' @return  A ggplot object representing the loadings plot for the specified multivariate model.
#' @export
#'
#' @examples \dontrun{
#' # Example usage:
#' model <- some_ropls_model   # Replace with your model object
#' bin_info <- data.frame(Metabolite = c("Met1", "Met2"), Bins = c(0.12, 0.34))
#' Plot_loading(model, comp = c(1, 2), point = TRUE, bin_identification = bin_info)
#' }
#'
Plot_loading <- function(model,comp=c(1,2),point = T,repel = F,font.label = c(12,"plain"),
                         bin_identification=NULL,bins_roundPrecision=4,VIP_roundPrecision=2,show_metabolite_name=T,
                         VIP_values_scale=NULL,theme=NULL){

  model_data <- extract_ropls_data(model,bins_roundPrecision = bins_roundPrecision,VIP_roundPrecision = VIP_roundPrecision)

  label <- "bins"

  if(!is.null(bin_identification)){

    identified_bins <- dplyr::filter(model_data$Loadings,bins%in%bin_identification[[2]])
    bins_name <- colnames(bin_identification)[[2]]
    identified_bins <- dplyr::left_join(identified_bins,bin_identification,by=c("bins"=bins_name))
    model_data$Loadings <- identified_bins

    if (show_metabolite_name==T) label <- colnames(bin_identification)[[1]]
    }


  if(model@typeC=="PCA"){

    PCA_data <- model_data

    loading_plot <- ggpubr::ggscatter(PCA_data$Loadings,
                                      x=paste("p",comp[1],sep = ""),
                                      y=paste("p",comp[2],sep = ""),
                                      size = 2,label = label,point=point,
                      repel = repel,font.label = font.label)+
      ggplot2::labs(x=paste("PC",comp[1]," (",model@modelDF$R2X[comp[1]]*100,"%)"),
                    y=paste("PC",comp[2]," (",model@modelDF$R2X[comp[2]]*100,"%)"),
                    title = model@typeC)+
      ggplot2::theme_bw()
  }


  if(model@typeC=="PLS-DA"||model@typeC=="PLS"){

    PLS_data <- model_data

    loading_plot <- ggpubr::ggscatter(PLS_data$Loadings,
                                      x=paste("p",comp[1],sep = ""),
                                      y=paste("p",comp[2],sep = ""),
                                      size = 2,label = label,point=point,
                                      repel = repel,font.label = font.label,color="Vip")+
                    ggplot2::labs(x=paste("Comp",comp[1]," (",model@modelDF$R2X[comp[1]]*100,"%)"),
                                  y=paste("Comp",comp[2]," (",model@modelDF$R2X[comp[2]]*100,"%)"),
                                  title = model@typeC)+
                    ggplot2::scale_color_gradientn(colours = c("black","#ff0000"),
                                                   values = VIP_values_scale)+
                    ggplot2::theme_bw()

  }


  if(model@typeC=="OPLS-DA"||model@typeC=="OPLS"){

    OPLS_data <- model_data

    loading_plot <- ggpubr::ggscatter(OPLS_data$Loadings,
                    x=if(comp[1]==1) paste("p",comp[1],sep = "") else paste("o",comp[1]-1,sep = ""),
                    y= if(comp[2]==1) paste("p",comp[2],sep = "") else paste("o",comp[2]-1,sep = ""),
                    size = 2,label = label,point=point,
                    repel = repel,font.label = font.label,color="Vip")+
      ggplot2::labs(x=paste(if(comp[1]==1) paste("Pred. Comp") else paste("Ortho. Comp"),comp[1]," (",model@modelDF$R2X[comp[1]]*100,"%)"),
                    y=paste(if(comp[2]==1) paste("Pred. Comp") else paste("Ortho. Comp"),comp[2]," (",model@modelDF$R2X[comp[2]]*100,"%)"),
                    title = model@typeC)+
      ggplot2::scale_color_gradientn(colours = c("black","#ff0000"),values = VIP_values_scale)+
      ggplot2::theme_bw()

  }

  return(loading_plot+theme)
}



#' Plot Loadings of a Multivariate Model
#'
#' This function generates a loading plot for PCA, PLS, PLS-DA, OPLS, or OPLS-DA models.
#' It visualizes the importance of variables in different components and should be used
#' instead of `Plot_scores` when the predictor variables in the model do not correspond to a spectrum.
#'
#' @param model An object containing a PCA, PLS, PLS-DA, OPLS, or OPLS-DA model from the ROPLS package.
#' @param comp A numeric vector of length 2 specifying the components to be plotted. Default is c(1,2).
#' @param point Logical. If TRUE, points representing variables are displayed. Default is TRUE.
#' @param repel Logical. If TRUE, labels are repelled to avoid overlap. Default is FALSE.
#' @param font.label A vector specifying font size, style, and color for variable labels. See `ggscatter` from `ggpubr` for details.
#' @param bins_roundPrecision Numeric. Number of decimal places for rounding bin values. Default is 4.
#' @param VIP_roundPrecision Numeric. Number of decimal places for rounding VIP values. Default is 2.
#' @param VIP_values_scale Numeric vector. Scale values for VIP coloring gradient.Use a vector of length 3 were the first value represents
#' the lower point of the scale, followed by the middle point and the highest point.
#' @param theme A `ggplot2` theme object for customizing the plot appearance.
#'
#' @return A `ggplot2` object displaying the loading plot.
#'
#' @details
#' - For PCA models, variables are colored uniformly.
#' - For PLS and PLS-DA models, variables are colored according to their VIP scores.
#' - For OPLS and OPLS-DA models, predictive (`p`) and orthogonal (`o`) components are correctly labeled on the axes.
#'
#' This function should be used instead of `Plot_scores` when the variables used as predictors in the model
#' do not correspond to a spectrum.
#'
#' @export
#'
#' @examples
#' \dontrun{
#' Plot_loading2(model, comp = c(1,2), point = TRUE, repel = FALSE, font.label = c(12, "plain"))
#' }

Plot_loading2 <- function(model,comp=c(1,2),point = T,repel = F,font.label = c(12,"plain"),
                          bins_roundPrecision=4,VIP_roundPrecision=2,
                          VIP_values_scale=NULL,theme=NULL){

  model_data <- extract_ropls_data(model,bins_roundPrecision = bins_roundPrecision,VIP_roundPrecision = VIP_roundPrecision)
  model_data$Loadings$bins <- rownames(model_data$Loadings)

  label <- "bins"

  if(model@typeC=="PCA"){

    PCA_data <- model_data

    loading_plot <- ggpubr::ggscatter(PCA_data$Loadings,
                                      x=paste("p",comp[1],sep = ""),
                                      y=paste("p",comp[2],sep = ""),
                                      size = 2,label = label,point=point,
                                      repel = repel,font.label = font.label)+
      ggplot2::labs(x=paste("PC",comp[1]," (",model@modelDF$R2X[comp[1]]*100,"%)"),
                    y=paste("PC",comp[2]," (",model@modelDF$R2X[comp[2]]*100,"%)"),
                    title = model@typeC)+
      ggplot2::theme_bw()
  }


  if(model@typeC=="PLS-DA"||model@typeC=="PLS"){

    PLS_data <- model_data

    loading_plot <- ggpubr::ggscatter(PLS_data$Loadings,
                                      x=paste("p",comp[1],sep = ""),
                                      y=paste("p",comp[2],sep = ""),
                                      size = 2,label = label,point=point,
                                      repel = repel,font.label = font.label,color="Vip")+
      ggplot2::labs(x=paste("Comp",comp[1]," (",model@modelDF$R2X[comp[1]]*100,"%)"),
                    y=paste("Comp",comp[2]," (",model@modelDF$R2X[comp[2]]*100,"%)"),
                    title = model@typeC)+
      ggplot2::scale_color_gradientn(colours = c("black","#ff0000"),
                                     values = VIP_values_scale)+
      ggplot2::theme_bw()

  }


  if(model@typeC=="OPLS-DA"||model@typeC=="OPLS"){

    OPLS_data <- model_data

    loading_plot <- ggpubr::ggscatter(OPLS_data$Loadings,
                                      x=if(comp[1]==1) paste("p",comp[1],sep = "") else paste("o",comp[1]-1,sep = ""),
                                      y= if(comp[2]==1) paste("p",comp[2],sep = "") else paste("o",comp[2]-1,sep = ""),
                                      size = 2,label = label,point=point,
                                      repel = repel,font.label = font.label,color="Vip")+
      ggplot2::labs(x=paste(if(comp[1]==1) paste("Pred. Comp") else paste("Ortho. Comp"),comp[1]," (",model@modelDF$R2X[comp[1]]*100,"%)"),
                    y=paste(if(comp[2]==1) paste("Pred. Comp") else paste("Ortho. Comp"),comp[2]," (",model@modelDF$R2X[comp[2]]*100,"%)"),
                    title = model@typeC)+
      ggplot2::scale_color_gradientn(colours = c("black","#ff0000"),values = VIP_values_scale)+
      ggplot2::theme_bw()

  }

  return(loading_plot+theme)
}

#' Overview of PCA Loadings
#'
#' This function provides an overview of the loadings from a PCA model,
#' arranging loading plots for consecutive principal components (PC1 vs PC2, PC3 vs PC4, etc.).
#'
#' @param PCA_object A PCA object containing the loadings to be visualized.
#' @param label_size Font size for variable labels in the plot. Default: 7.
#' @param plot_font_size Font size for text elements in the plot. Default: 7.
#' @param repel Logical. If TRUE, variable labels are adjusted to avoid overlap. Default: FALSE.
#' @param show_points Logical. If TRUE, displays points representing variables in the plot. Default: TRUE.
#' @param add Additional graphical elements to be included in the plots. Default: NULL.
#' @param scale_expansion Axis expansion factor for better visualization. Default: 0.15.
#' @param return_list Logical. If TRUE, returns a list of individual plots instead of a combined plot. Default: FALSE.
#'
#' @return A combined plot of PCA loadings for multiple principal components.
#' If `return_list = TRUE`, returns a list of individual plots.
#'
#' @export
#'
#' @examples
#' \dontrun{
#' # Assuming `pca_model` is a valid PCA object:
#' plot_loading_overview(pca_model)
#' }
#'
plot_loading_overview <- function(PCA_object,
                                  label_size = 7,
                                  plot_font_size = 7,
                                  repel = F,
                                  show_points = T,
                                  add = NULL,
                                  scale_expansion = 0.15,
                                  return_list = F) {
  ncomps <- PCA_object@summaryDF$pre
  pca_loading_list <- list()

  for (i in seq(1, ncomps, 2)) {
    if (i == ncomps)
      break

    pca_loading_list[[length(pca_loading_list) + 1]] <- Plot_loading2(
      PCA_object,
      comp = c(i, i + 1),
      point = show_points,
      repel = repel,
      font.label = label_size
    ) +
      ggplot2::theme(
        plot.title = ggplot2::element_blank(),
        axis.title = ggplot2::element_text(size = plot_font_size),
        legend.text = ggplot2::element_text(size = plot_font_size),
        legend.title = ggplot2::element_text(size = plot_font_size),
        axis.text = ggplot2::element_text(size = plot_font_size)
      ) + ggplot2::scale_x_continuous(expand = ggplot2::expansion(mult = scale_expansion)) +
          ggplot2::scale_y_continuous(expand = ggplot2::expansion(mult = scale_expansion)) +
      add
  }

  if (return_list) {
    return(pca_loading_list)
  } else{
    patchwork::wrap_plots(pca_loading_list)
  }
}



#' Plot Loading Profiles for PCA, PLS(-DA), or OPLS(-DA) Models
#'
#' This function generates loading plots for multivariate models produced by
#' \code{ropls}, supporting PCA, PLS, PLS-DA, OPLS, and OPLS-DA.
#' Loadings are displayed as vertical bars along the chemical shift axis.
#' For supervised methods (PLS/OPLS), VIP values can be used to color the bars.
#' Plots can be returned as static \code{ggplot2} figures or converted to
#' interactive \code{plotly} visualizations.
#'
#' @param model An \code{ropls} model object (PCA, PLS(-DA), or OPLS(-DA)).
#'
#' @param comp Integer. Component to plot (default = 1).
#'
#' @param interactive Logical (default = TRUE).
#' If \code{TRUE}, the function returns an interactive \code{plotly} object;
#'   otherwise, a static \code{ggplot2} plot.
#'
#' @param VIP_values_scale Optional numeric vector of length 2 defining the scale
#' used in \code{ggplot2::scale_fill_gradientn()} for VIP coloring
#'   (used only for PLS/OPLS models).
#'   Example: \code{c(0, 1)}.
#'
#' @param theme Optional \code{ggplot2} theme object to add to the final plot.
#' Example: \code{ggplot2::theme_minimal()}.
#'
#' @returns
#' A \code{plotly} interactive plot if \code{interactive = TRUE},
#' otherwise a \code{ggplot2} object representing the loading plot.
#'
#' @export
#'
#' @examples
#' \dontrun{
#' # Fit a PCA model with ropls
#' pca_model <- ropls::opls(X, predI = 3)
#'
#' # Plot first principal component loadings
#' plot_loading_lines(pca_model, comp = 1)
#'
#' # Plot PLS-DA loadings with VIP scaling
#' plsda_model <- ropls::opls(X, Y, predI = 2)
#' plot_loading_lines(
#'   model = plsda_model,
#'   comp = 1,
#'   VIP_values_scale = c(0, 2),
#'   theme = ggplot2::theme_minimal()
#' )
#'
#' # Static version
#' plot_loading_lines(pca_model, interactive = FALSE)
#' }
#'
plot_loading_lines <- function (model,
                                comp = 1,
                                interactive=T,
                                VIP_values_scale = NULL,
                                theme = NULL)
{
  model_data <- extract_ropls_data(model)

  if (model@typeC == "PCA") {

    PCA_data <- model_data
    loading_data <- data.frame(
      "bins"=as.numeric(PCA_data$Loadings$bins),
      "loadings"=PCA_data$Loadings[[comp+1]])

    loading_plot <- ggplot2::ggplot(
      loading_data) +
      ggplot2::aes(x=bins,
                   y=loadings) +
      ggplot2::geom_col(fill="black")+
      ggplot2::labs(
        title = paste("Loadings (",
                      model@typeC,
                      ")",
                      "-",
                      paste(
                        "PC",
                        comp,
                        " (",
                        model@modelDF$R2X[comp] * 100,
                        "%)")
        ),
        x = "Chemical shift (ppm)") +
      ggplot2::scale_x_reverse(breaks=seq(-0.5,12,0.5)) +
      ggplot2::theme_bw()


  }
  if (model@typeC == "PLS-DA" || model@typeC == "PLS") {

    PLS_data <- model_data
    Vip_values <- dplyr::select(PLS_data$Loadings,
                                bins,
                                Vip)
    loading_values <- dplyr::select(PLS_data$Loadings,
                                    -Vip)

    loading_data <- data.frame(
      "bins"=as.numeric(PLS_data$Loadings$bins),
      "loadings"=loading_values[[comp+1]],
      "Vip"=Vip_values$Vip)

    loading_plot <- ggplot2::ggplot(
      loading_data) +
      ggplot2::aes(x=bins,
                   y=loadings,
                   fill=Vip) +
      ggplot2::geom_col()+
      ggplot2::scale_fill_gradientn(
        colours = c("black","#ff0000"),
        values = VIP_values_scale) +
      ggplot2::labs(
        title = paste("Loadings (",
                      model@typeC,
                      ")",
                      "-",
                      paste(
                        "Comp",
                        comp,
                        " (",
                        model@modelDF$R2X[comp] * 100,
                        "%)")
        ),
        x = "Chemical shift (ppm)") +
      ggplot2::scale_x_reverse(breaks=seq(-0.5,12,0.5)) +
      ggplot2::theme_bw()


  }
  if (model@typeC == "OPLS-DA" || model@typeC == "OPLS") {

    OPLS_data <- model_data

    Vip_values <- dplyr::select(OPLS_data$Loadings,
                                bins,
                                Vip)
    loading_values <- dplyr::select(OPLS_data$Loadings,
                                    -Vip)

    loading_data <- data.frame(
      "bins"=as.numeric(OPLS_data$Loadings$bins),
      "loadings"=loading_values[[comp+1]],
      "Vip"=Vip_values$Vip)

    loading_plot <- ggplot2::ggplot(
      loading_data) +
      ggplot2::aes(x=bins,
                   y=loadings,
                   fill=Vip) +
      ggplot2::geom_col()+
      ggplot2::scale_fill_gradientn(
        colours = c("black","#ff0000"),
        values = VIP_values_scale) +
      ggplot2::labs(
        title = paste("Loadings (",
                      model@typeC,
                      ")",
                      "-",
                      paste(if (comp == 1)
                        paste("Pred. Comp")
                        else paste("Ortho. Comp"),
                        comp[1],
                        " (",
                        model@modelDF$R2X[comp] *
                          100,
                        "%)")
        ),
        x = "Chemical shift (ppm)") +
      ggplot2::scale_x_reverse(breaks=seq(-0.5,12,0.5)) +
      ggplot2::theme_bw()

  }

  if (interactive==T) return(plotly::ggplotly(loading_plot + theme)) else
    return(loading_plot + theme)

}


#' Plot S-Lines for PLS(-DA) Models
#'
#'  Generates S-line plots to visualize the covariance and correlation of variables
#' with the scores of a selected component from a OPLS(-DA), PLS(-DA) or PCA model.
#' This plot provides insight into the contribution of each variable to the selected component.
#'
#' @param TrainingData A matrix or data frame containing the original data used for model training.
#' Variables are represented as columns, and samples as rows.
#' @param model A OPLS(-DA), PLS(-DA) or PCA model generated using the `ropls` package.
#' @param comp A numeric value specifying the component to be analyzed. Default is `1`.
#' @param interactive Logical. If `TRUE`, returns an interactive plot using `plotly`.
#' If `FALSE`, returns a static `ggplot2` plot. Default is `TRUE`.
#'
#' @description
#'
#' Creates an S-line plot to show the relationship between variables and the scores of a selected
#' component. The plot displays the covariance (`Cov(Tp, X)`) on the y-axis and the chemical shift (ppm)
#' on the x-axis. The fill color represents the absolute correlation (`|Cor(Tp, X)|`),
#' highlighting variables that contribute most to the selected component.
#'
#' @return
#' A plot object. Returns a `ggplot2` object for static plots or a `plotly` object for interactive plots.
#' @export
#'
#' @examples \dontrun{
#' # Example usage:
#' TrainingData <- some_data_matrix  # Replace with your dataset
#' model <- some_ropls_model         # Replace with your PLS-DA or PCA model
#' plot_slines_PLS(TrainingData, model, comp = 1, interactive = TRUE)
#' }
#'
plot_slines <- function(TrainingData,model,comp=1,interactive=T){
  PLS_data <- extract_ropls_data(model)

  if(model@typeC=="PCA"){
    metadataColuns=1
  }else{
    metadataColuns=c(1,2)
  }

  cov_pls <- as.data.frame(cov(TrainingData,PLS_data$Scores[-metadataColuns]))
  cor_pls <- as.data.frame(cor(TrainingData,PLS_data$Scores[-metadataColuns]))

  slines_data <- data.frame(
    "bins"=as.numeric(rownames(cov_pls)),
    "cor"=cor_pls[,comp],
    "cov"=cov_pls[,comp])

  slines_plot <- ggplot2::ggplot(slines_data,ggplot2::aes(bins,cov,fill=abs(cor)))+
    ggplot2::geom_hline(yintercept = 0)+
    ggplot2::geom_col()+
    ggplot2::scale_fill_gradientn(colours = c("blue","green","red"),
                         values = c(0,0.6,1))+
    ggplot2::theme_bw()+
    ggplot2::scale_x_reverse(breaks = seq(-0.5,12,0.5))+
    ggplot2::labs(title = paste("Slines (",model@typeC,")","-","Comp",comp),
         y="Cov(Tp,X)",
         x="Chemical shift (ppm)",
         fill="Abs(Cor(Tp,X))")

  if(interactive==T){
    return(plotly::ggplotly(slines_plot))
  }else{
    return(slines_plot)
  }
}
