
#' Plot Scores for Multivariate Models
#'
#'  This function generates a scores plot for multivariate models created using the `ropls` package,
#' including PCA, PLS(-DA), and OPLS(-DA). It provides advanced customization options for visualization
#' using `ggplot2`, allowing the addition of ellipses, sample labels, and group-based coloring.
#'
#' @param model A list containing a model of type PCA, PLS-DA, OPLS-DA, PLS, or OPLS, generated by the `ropls` package.
#' @param groups A vector specifying sample groups used for coloring and identifying samples in PCA models.
#' In supervised models (PLS-DA, OPLS-DA), the groups are automatically defined by the model.
#' @param comp A numeric vector of length 2 specifying the components to be plotted. Defaults to `c(1, 2)`.
#' @param point_size Numeric. Defines the size of the points in the plot (default: `2`).
#' @param ellipse Logical. If `TRUE`, confidence interval ellipses are displayed around groups (default: `TRUE`).
#' @param labels  Logical or vector. If `TRUE`, sample names are displayed as labels.
#' Alternatively, a custom vector of sample names can be provided. If `FALSE`, no labels are shown (default: `TRUE`).
#' @param font.label A vector specifying the font size, color, and style for sample labels. For details, see
#' the `font.label` argument in the `ggscatter` function from the `ggpubr` package.
#' @param point Logical. If `TRUE`, points representing samples are displayed in the plot (default: `TRUE`).
#' @param repel_labels Logical. If `TRUE`, sample labels are adjusted to avoid overlap (default: `FALSE`).
#' @param theme A ggplot2 theme for customizing the plot appearance. If `NULL`, the default theme `theme_bw` is used.
#'
#' @description
#'  Provides an easy way to generate scores plots from models generated by the `ropls` package,
#' with advanced customization options such as group-based coloring, confidence ellipses,
#' and flexible label positioning.
#'
#' @return
#' A `ggplot2` object representing the scores plot for the specified multivariate model.
#'
#' @export
#'
#' @examples \dontrun{
#' # Example usage:
#' model <- some_ropls_model   # Replace with your PCA, PLS-DA, or OPLS-DA model
#' groups <- c("Group1", "Group2", "Group1", "Group2")  # Define sample groups for coloring
#' Plot_scores(model, groups = groups, comp = c(1, 2), ellipse = TRUE, labels = TRUE)
#'}
#'
Plot_scores <- function(model,groups=NULL,comp=c(1,2),point_size=2,ellipse=T,labels=T,font.label=c(12,"plain"),point=T,repel_labels=F,theme=NULL){

  if(model@typeC=="PCA"){

    PCA_data <- extract_ropls_data(model)
    legend.text=F

    if(!is.null(groups)){
      PCA_data$Scores$Group <- groups
      Group <- "Group"
      col_group <- Group
      group_alpha=0.3
      Legend=T
    }else{
      col_group = "black"
      Group <- NULL
      group_alpha=0
      Legend=F
    }

    if(ellipse==F){
      group_alpha <- 0
    }

    if(length(labels)==1&&labels==T){
      plot_label="Samples"
    }else{
      if(length(labels)==1&&labels==F){
        plot_label=NULL
      }else{
        PCA_data$Scores$Samples <- labels
        plot_label="Samples"
      }
    }
    if(point==F){
      legend.text=NA
    }

    scores_plot <- ggpubr::ggscatter(PCA_data$Scores,x=paste("p",comp[1],sep = ""),y=paste("p",comp[2],sep = ""),color=col_group,
              size = point_size,label = plot_label,point = point,
              font.label = font.label,repel = repel_labels,show.legend.text = legend.text)+
      ggplot2::stat_ellipse(ggplot2::aes(color=if(ellipse==T) eval(Group),fill=if(ellipse==T) eval(Group)),geom = "polygon",
                            alpha=group_alpha,show.legend = F)+
      ggplot2::labs(x=paste("PC",comp[1]," (",model@modelDF$R2X[comp[1]]*100,"%)"),
           y=paste("PC",comp[2]," (",model@modelDF$R2X[comp[2]]*100,"%)"),
           title = model@typeC)+
      ggplot2::theme_bw()+ggplot2::theme(legend.text = ggplot2::element_text(size = 14),
                       axis.text = ggplot2::element_text(size=14),
                       axis.title = ggplot2::element_text(size = 14),
                       legend.position = "bottom")

  }

  if(model@typeC=="PLS-DA"||model@typeC=="PLS"){

    PLS_data <- extract_ropls_data(model)
    Group <- "Group"
    col_group <- Group
    group_alpha=0.3
    Legend=T
    legend.text=F

    if(ellipse==F){
      group_alpha <- 0
    }

    if(length(labels)==1&&labels==T){
      plot_label="Samples"
    }else{
      if(length(labels)==1&&labels==F){
        plot_label=NULL
      }else{
        PLS_data$Scores$Samples <- labels
        plot_label="Samples"
      }
    }
    if(point==F){
      legend.text=NA
    }

    scores_plot <- ggpubr::ggscatter(PLS_data$Scores,x=paste("p",comp[1],sep = ""),y=paste("p",comp[2],sep = ""),color=col_group,
                             size = point_size,label = plot_label,point = point,
                             font.label = font.label,repel = repel_labels,show.legend.text = legend.text)+
      ggplot2::stat_ellipse(ggplot2::aes(color=if(ellipse==T) eval(Group),fill=if(ellipse==T) eval(Group)),geom = "polygon",
                            alpha=group_alpha,show.legend = F)+
      ggplot2::labs(x=paste("Comp",comp[1]," (",model@modelDF$R2X[comp[1]]*100,"%)"),
           y=paste("Comp",comp[2]," (",model@modelDF$R2X[comp[2]]*100,"%)"),
           title = model@typeC)+
      ggplot2::theme_bw()+ggplot2::theme(legend.text = ggplot2::element_text(size = 14),
                       axis.text = ggplot2::element_text(size=14),
                       axis.title = ggplot2::element_text(size = 14),
                       legend.position = "bottom")

  }

  if(model@typeC=="OPLS-DA"||model@typeC=="OPLS"){

    PLS_data <- extract_ropls_data(model)
    Group <- "Group"
    col_group <- Group
    group_alpha=0.3
    Legend=T
    legend.text=F

    if(ellipse==F){
      group_alpha <- 0
    }

    if(length(labels)==1&&labels==T){
      plot_label="Samples"
    }else{
      if(length(labels)==1&&labels==F){
        plot_label=NULL
      }else{
        PLS_data$Scores$Samples <- labels
        plot_label="Samples"
      }
    }
    if(point==F){
      legend.text=NA
    }

    scores_plot <- ggpubr::ggscatter(PLS_data$Scores,
                                     x=if(comp[1]==1) paste("p",comp[1],sep = "") else paste("o",comp[1]-1,sep = ""),
                                     y= if(comp[2]==1) paste("p",comp[2],sep = "") else paste("o",comp[2]-1,sep = ""),
                                     color=col_group,
                                    size = point_size,label = plot_label,point = point,
                                    font.label = font.label,repel = repel_labels,show.legend.text = legend.text)+
                  ggplot2::stat_ellipse(ggplot2::aes(color=if(ellipse==T) eval(Group),fill=if(ellipse==T) eval(Group)),geom = "polygon",
                                                      alpha=group_alpha,show.legend = F)+
                  ggplot2::labs(x=paste(if(comp[1]==1) paste("Pred. Comp") else paste("Ortho. Comp"),comp[1]," (",model@modelDF$R2X[comp[1]]*100,"%)"),
                                y=paste(if(comp[2]==1) paste("Pred. Comp") else paste("Ortho. Comp"),comp[2]," (",model@modelDF$R2X[comp[2]]*100,"%)"),
                                title = model@typeC)+
                  ggplot2::theme_bw()+ggplot2::theme(legend.text = ggplot2::element_text(size = 14),
                                                      axis.text = ggplot2::element_text(size=14),
                                                      axis.title = ggplot2::element_text(size = 14),
                                                      legend.position = "bottom")

  }

  return(scores_plot+theme)
}








#'  Plot Loadings for Multivariate Models
#'
#'  This function generates a scatter plot of loadings for multivariate models, including PCA, PLS(-DA), and OPLS(-DA).
#' The function allows for customization of various plot parameters, enabling the identification and visualization
#' of important features (e.g., bins or metabolites) within the model. It supports options to label identified bins,
#' control the precision of rounding for bin and VIP values, and apply custom themes.
#'
#' @param model An object of class `ropls`, representing the multivariate model (PCA, PLS(-DA), or OPLS(-DA)) for which loadings are plotted.
#' @param comp A numeric vector of length 2 indicating the components to be plotted (default: `c(1, 2)`).
#' @param point Logical. If `TRUE`, points are displayed in the plot (default: `TRUE`).
#' @param repel Logical. If `TRUE`, labels are adjusted to repel each other, reducing overlap (default: `FALSE`).
#' @param font.label A vector indicating the font size and style of labels (e.g., `c(12, "plain")`).
#' @param bin_identification A data frame with two columns: the first column for metabolite names and the second for corresponding bins. Used to annotate bins.
#' @param bins_roundPrecision Integer. Specifies the number of decimal places for rounding bin values (default: `4`).
#' @param VIP_roundPrecision Integer. Specifies the number of decimal places for rounding VIP (Variable Importance in Projection) values (default: `2`).
#' @param show_metabolite_name Logical. If `TRUE`, metabolite names are displayed in labels when `bin_identification` is provided (default: `TRUE`).
#' @param VIP_values_scale A numeric vector of values to scale the color gradient for VIP values. If `NULL`, a default scale is applied. Use a vector of length 3 were the first value represents
#' the lower point of the scale, followed by the middle point and the highest point.
#' @param theme A ggplot2 theme to customize the plot appearance. If `NULL`, the default `theme_bw` is used.
#'
#' @return  A ggplot object representing the loadings plot for the specified multivariate model.
#' @export
#'
#' @examples \dontrun{
#' # Example usage:
#' model <- some_ropls_model   # Replace with your model object
#' bin_info <- data.frame(Metabolite = c("Met1", "Met2"), Bins = c(0.12, 0.34))
#' Plot_loading(model, comp = c(1, 2), point = TRUE, bin_identification = bin_info)
#' }
#'
Plot_loading <- function(model,comp=c(1,2),point = T,repel = F,font.label = c(12,"plain"),
                         bin_identification=NULL,bins_roundPrecision=4,VIP_roundPrecision=2,show_metabolite_name=T,
                         VIP_values_scale=NULL,theme=NULL){

  model_data <- extract_ropls_data(model,bins_roundPrecision = bins_roundPrecision,VIP_roundPrecision = VIP_roundPrecision)

  label <- "bins"

  if(!is.null(bin_identification)){

    identified_bins <- dplyr::filter(model_data$Loadings,bins%in%bin_identification[[2]])
    bins_name <- colnames(bin_identification)[[2]]
    identified_bins <- dplyr::left_join(identified_bins,bin_identification,by=c("bins"=bins_name))
    model_data$Loadings <- identified_bins

    if (show_metabolite_name==T) label <- colnames(bin_identification)[[1]]
    }


  if(model@typeC=="PCA"){

    PCA_data <- model_data

    loading_plot <- ggpubr::ggscatter(PCA_data$Loadings,
                                      x=paste("p",comp[1],sep = ""),
                                      y=paste("p",comp[2],sep = ""),
                                      size = 2,label = label,point=point,
                      repel = repel,font.label = font.label)+
      ggplot2::labs(x=paste("PC",comp[1]," (",model@modelDF$R2X[comp[1]]*100,"%)"),
                    y=paste("PC",comp[2]," (",model@modelDF$R2X[comp[2]]*100,"%)"),
                    title = model@typeC)+
      ggplot2::theme_bw()
  }


  if(model@typeC=="PLS-DA"||model@typeC=="PLS"){

    PLS_data <- model_data

    loading_plot <- ggpubr::ggscatter(PLS_data$Loadings,
                                      x=paste("p",comp[1],sep = ""),
                                      y=paste("p",comp[2],sep = ""),
                                      size = 2,label = label,point=point,
                                      repel = repel,font.label = font.label,color="Vip")+
                    ggplot2::labs(x=paste("Comp",comp[1]," (",model@modelDF$R2X[comp[1]]*100,"%)"),
                                  y=paste("Comp",comp[2]," (",model@modelDF$R2X[comp[2]]*100,"%)"),
                                  title = model@typeC)+
                    ggplot2::scale_color_gradientn(colours = c("black","#ff0000"),
                                                   values = VIP_values_scale)+
                    ggplot2::theme_bw()

  }


  if(model@typeC=="OPLS-DA"||model@typeC=="OPLS"){

    OPLS_data <- model_data

    loading_plot <- ggpubr::ggscatter(OPLS_data$Loadings,
                    x=if(comp[1]==1) paste("p",comp[1],sep = "") else paste("o",comp[1]-1,sep = ""),
                    y= if(comp[2]==1) paste("p",comp[2],sep = "") else paste("o",comp[2]-1,sep = ""),
                    size = 2,label = label,point=point,
                    repel = repel,font.label = font.label,color="Vip")+
      ggplot2::labs(x=paste(if(comp[1]==1) paste("Pred. Comp") else paste("Ortho. Comp"),comp[1]," (",model@modelDF$R2X[comp[1]]*100,"%)"),
                    y=paste(if(comp[2]==1) paste("Pred. Comp") else paste("Ortho. Comp"),comp[2]," (",model@modelDF$R2X[comp[2]]*100,"%)"),
                    title = model@typeC)+
      ggplot2::scale_color_gradientn(colours = c("black","#ff0000"),values = VIP_values_scale)+
      ggplot2::theme_bw()

  }

  return(loading_plot+theme)
}



#' Plot Loadings of a Multivariate Model
#'
#' This function generates a loading plot for PCA, PLS, PLS-DA, OPLS, or OPLS-DA models.
#' It visualizes the importance of variables in different components and should be used
#' instead of `Plot_scores` when the predictor variables in the model do not correspond to a spectrum.
#'
#' @param model An object containing a PCA, PLS, PLS-DA, OPLS, or OPLS-DA model from the ROPLS package.
#' @param comp A numeric vector of length 2 specifying the components to be plotted. Default is c(1,2).
#' @param point Logical. If TRUE, points representing variables are displayed. Default is TRUE.
#' @param repel Logical. If TRUE, labels are repelled to avoid overlap. Default is FALSE.
#' @param font.label A vector specifying font size, style, and color for variable labels. See `ggscatter` from `ggpubr` for details.
#' @param bins_roundPrecision Numeric. Number of decimal places for rounding bin values. Default is 4.
#' @param VIP_roundPrecision Numeric. Number of decimal places for rounding VIP values. Default is 2.
#' @param VIP_values_scale Numeric vector. Scale values for VIP coloring gradient.Use a vector of length 3 were the first value represents
#' the lower point of the scale, followed by the middle point and the highest point.
#' @param theme A `ggplot2` theme object for customizing the plot appearance.
#'
#' @return A `ggplot2` object displaying the loading plot.
#'
#' @details
#' - For PCA models, variables are colored uniformly.
#' - For PLS and PLS-DA models, variables are colored according to their VIP scores.
#' - For OPLS and OPLS-DA models, predictive (`p`) and orthogonal (`o`) components are correctly labeled on the axes.
#'
#' This function should be used instead of `Plot_scores` when the variables used as predictors in the model
#' do not correspond to a spectrum.
#'
#' @export
#'
#' @examples
#' \dontrun{
#' Plot_loading2(model, comp = c(1,2), point = TRUE, repel = FALSE, font.label = c(12, "plain"))
#' }

Plot_loading2 <- function(model,comp=c(1,2),point = T,repel = F,font.label = c(12,"plain"),
                          bins_roundPrecision=4,VIP_roundPrecision=2,
                          VIP_values_scale=NULL,theme=NULL){

  model_data <- extract_ropls_data(model,bins_roundPrecision = bins_roundPrecision,VIP_roundPrecision = VIP_roundPrecision)
  model_data$Loadings$bins <- rownames(model_data$Loadings)

  label <- "bins"

  if(model@typeC=="PCA"){

    PCA_data <- model_data

    loading_plot <- ggpubr::ggscatter(PCA_data$Loadings,
                                      x=paste("p",comp[1],sep = ""),
                                      y=paste("p",comp[2],sep = ""),
                                      size = 2,label = label,point=point,
                                      repel = repel,font.label = font.label)+
      ggplot2::labs(x=paste("PC",comp[1]," (",model@modelDF$R2X[comp[1]]*100,"%)"),
                    y=paste("PC",comp[2]," (",model@modelDF$R2X[comp[2]]*100,"%)"),
                    title = model@typeC)+
      ggplot2::theme_bw()
  }


  if(model@typeC=="PLS-DA"||model@typeC=="PLS"){

    PLS_data <- model_data

    loading_plot <- ggpubr::ggscatter(PLS_data$Loadings,
                                      x=paste("p",comp[1],sep = ""),
                                      y=paste("p",comp[2],sep = ""),
                                      size = 2,label = label,point=point,
                                      repel = repel,font.label = font.label,color="Vip")+
      ggplot2::labs(x=paste("Comp",comp[1]," (",model@modelDF$R2X[comp[1]]*100,"%)"),
                    y=paste("Comp",comp[2]," (",model@modelDF$R2X[comp[2]]*100,"%)"),
                    title = model@typeC)+
      ggplot2::scale_color_gradientn(colours = c("black","#ff0000"),
                                     values = VIP_values_scale)+
      ggplot2::theme_bw()

  }


  if(model@typeC=="OPLS-DA"||model@typeC=="OPLS"){

    OPLS_data <- model_data

    loading_plot <- ggpubr::ggscatter(OPLS_data$Loadings,
                                      x=if(comp[1]==1) paste("p",comp[1],sep = "") else paste("o",comp[1]-1,sep = ""),
                                      y= if(comp[2]==1) paste("p",comp[2],sep = "") else paste("o",comp[2]-1,sep = ""),
                                      size = 2,label = label,point=point,
                                      repel = repel,font.label = font.label,color="Vip")+
      ggplot2::labs(x=paste(if(comp[1]==1) paste("Pred. Comp") else paste("Ortho. Comp"),comp[1]," (",model@modelDF$R2X[comp[1]]*100,"%)"),
                    y=paste(if(comp[2]==1) paste("Pred. Comp") else paste("Ortho. Comp"),comp[2]," (",model@modelDF$R2X[comp[2]]*100,"%)"),
                    title = model@typeC)+
      ggplot2::scale_color_gradientn(colours = c("black","#ff0000"),values = VIP_values_scale)+
      ggplot2::theme_bw()

  }

  return(loading_plot+theme)
}



#' Plot S-Lines for PLS(-DA) Models
#'
#'  Generates S-line plots to visualize the covariance and correlation of variables
#' with the scores of a selected component from a OPLS(-DA), PLS(-DA) or PCA model.
#' This plot provides insight into the contribution of each variable to the selected component.
#'
#' @param TrainingData A matrix or data frame containing the original data used for model training.
#' Variables are represented as columns, and samples as rows.
#' @param model A OPLS(-DA), PLS(-DA) or PCA model generated using the `ropls` package.
#' @param comp A numeric value specifying the component to be analyzed. Default is `1`.
#' @param interactive Logical. If `TRUE`, returns an interactive plot using `plotly`.
#' If `FALSE`, returns a static `ggplot2` plot. Default is `TRUE`.
#'
#' @description
#'
#' Creates an S-line plot to show the relationship between variables and the scores of a selected
#' component. The plot displays the covariance (`Cov(Tp, X)`) on the y-axis and the chemical shift (ppm)
#' on the x-axis. The fill color represents the absolute correlation (`|Cor(Tp, X)|`),
#' highlighting variables that contribute most to the selected component.
#'
#' @return
#' A plot object. Returns a `ggplot2` object for static plots or a `plotly` object for interactive plots.
#' @export
#'
#' @examples \dontrun{
#' # Example usage:
#' TrainingData <- some_data_matrix  # Replace with your dataset
#' model <- some_ropls_model         # Replace with your PLS-DA or PCA model
#' plot_slines_PLS(TrainingData, model, comp = 1, interactive = TRUE)
#' }
#'
plot_slines <- function(TrainingData,model,comp=1,interactive=T){
  PLS_data <- extract_ropls_data(model)

  if(model@typeC=="PCA"){
    metadataColuns=1
  }else{
    metadataColuns=c(1,2)
  }

  cov_pls <- as.data.frame(cov(TrainingData,PLS_data$Scores[-metadataColuns]))
  cor_pls <- as.data.frame(cor(TrainingData,PLS_data$Scores[-metadataColuns]))

  slines_data <- data.frame(
    "bins"=as.numeric(rownames(cov_pls)),
    "cor"=cor_pls[,comp],
    "cov"=cov_pls[,comp])

  slines_plot <- ggplot2::ggplot(slines_data,ggplot2::aes(bins,cov,fill=abs(cor)))+
    ggplot2::geom_hline(yintercept = 0)+
    ggplot2::geom_col()+
    ggplot2::scale_fill_gradientn(colours = c("blue","green","red"),
                         values = c(0,0.6,1))+
    ggplot2::theme_bw()+
    ggplot2::scale_x_reverse(breaks = seq(-0.5,12,0.5))+
    ggplot2::labs(title = paste("Slines (",model@typeC,")","-","Comp",comp),
         y="Cov(Tp,X)",
         x="Chemical shift (ppm)",
         fill="Abs(Cor(Tp,X))")

  if(interactive==T){
    return(plotly::ggplotly(slines_plot))
  }else{
    return(slines_plot)
  }
}
